/* soapH.h
   Generated by gSOAP 2.7.14 from modbus.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_short
#define SOAP_TYPE_short (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_short(struct soap*, short *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_short(struct soap*, const short *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_short(struct soap*, const char*, int, const short *, const char*);
SOAP_FMAC3 short * SOAP_FMAC4 soap_get_short(struct soap*, short *, const char*, const char*);
SOAP_FMAC3 short * SOAP_FMAC4 soap_in_short(struct soap*, const char*, short *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_long
#define SOAP_TYPE_long (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_long(struct soap*, long *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_long(struct soap*, const long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_long(struct soap*, const char*, int, const long *, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_get_long(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_in_long(struct soap*, const char*, long *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedShort
#define SOAP_TYPE_unsignedShort (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedShort(struct soap*, unsigned short *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedShort(struct soap*, const unsigned short *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedShort(struct soap*, const char*, int, const unsigned short *, const char*);
SOAP_FMAC3 unsigned short * SOAP_FMAC4 soap_get_unsignedShort(struct soap*, unsigned short *, const char*, const char*);
SOAP_FMAC3 unsigned short * SOAP_FMAC4 soap_in_unsignedShort(struct soap*, const char*, unsigned short *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_unsignedLong
#define SOAP_TYPE_unsignedLong (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedLong(struct soap*, unsigned long *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedLong(struct soap*, const unsigned long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedLong(struct soap*, const char*, int, const unsigned long *, const char*);
SOAP_FMAC3 unsigned long * SOAP_FMAC4 soap_get_unsignedLong(struct soap*, unsigned long *, const char*, const char*);
SOAP_FMAC3 unsigned long * SOAP_FMAC4 soap_in_unsignedLong(struct soap*, const char*, unsigned long *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_ns__mb_master_config
#define SOAP_TYPE_ns__mb_master_config (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__mb_master_config(struct soap*, struct ns__mb_master_config *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__mb_master_config(struct soap*, const struct ns__mb_master_config *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__mb_master_config(struct soap*, const struct ns__mb_master_config *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__mb_master_config(struct soap*, const char*, int, const struct ns__mb_master_config *, const char*);
SOAP_FMAC3 struct ns__mb_master_config * SOAP_FMAC4 soap_get_ns__mb_master_config(struct soap*, struct ns__mb_master_config *, const char*, const char*);
SOAP_FMAC3 struct ns__mb_master_config * SOAP_FMAC4 soap_in_ns__mb_master_config(struct soap*, const char*, struct ns__mb_master_config *, const char*);

#ifndef SOAP_TYPE_ns__mb_master_configResponse
#define SOAP_TYPE_ns__mb_master_configResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__mb_master_configResponse(struct soap*, struct ns__mb_master_configResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__mb_master_configResponse(struct soap*, const struct ns__mb_master_configResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__mb_master_configResponse(struct soap*, const struct ns__mb_master_configResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__mb_master_configResponse(struct soap*, const char*, int, const struct ns__mb_master_configResponse *, const char*);
SOAP_FMAC3 struct ns__mb_master_configResponse * SOAP_FMAC4 soap_get_ns__mb_master_configResponse(struct soap*, struct ns__mb_master_configResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__mb_master_configResponse * SOAP_FMAC4 soap_in_ns__mb_master_configResponse(struct soap*, const char*, struct ns__mb_master_configResponse *, const char*);

#ifndef SOAP_TYPE_ns__mb_master_consulta
#define SOAP_TYPE_ns__mb_master_consulta (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__mb_master_consulta(struct soap*, struct ns__mb_master_consulta *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__mb_master_consulta(struct soap*, const struct ns__mb_master_consulta *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__mb_master_consulta(struct soap*, const struct ns__mb_master_consulta *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__mb_master_consulta(struct soap*, const char*, int, const struct ns__mb_master_consulta *, const char*);
SOAP_FMAC3 struct ns__mb_master_consulta * SOAP_FMAC4 soap_get_ns__mb_master_consulta(struct soap*, struct ns__mb_master_consulta *, const char*, const char*);
SOAP_FMAC3 struct ns__mb_master_consulta * SOAP_FMAC4 soap_in_ns__mb_master_consulta(struct soap*, const char*, struct ns__mb_master_consulta *, const char*);

#ifndef SOAP_TYPE_mb_master_config
#define SOAP_TYPE_mb_master_config (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mb_master_config(struct soap*, struct mb_master_config *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mb_master_config(struct soap*, const struct mb_master_config *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_mb_master_config(struct soap*, const struct mb_master_config *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mb_master_config(struct soap*, const char*, int, const struct mb_master_config *, const char*);
SOAP_FMAC3 struct mb_master_config * SOAP_FMAC4 soap_get_mb_master_config(struct soap*, struct mb_master_config *, const char*, const char*);
SOAP_FMAC3 struct mb_master_config * SOAP_FMAC4 soap_in_mb_master_config(struct soap*, const char*, struct mb_master_config *, const char*);

#ifndef SOAP_TYPE_mb_pdu_decimal
#define SOAP_TYPE_mb_pdu_decimal (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mb_pdu_decimal(struct soap*, struct mb_pdu_decimal *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mb_pdu_decimal(struct soap*, const struct mb_pdu_decimal *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_mb_pdu_decimal(struct soap*, const struct mb_pdu_decimal *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mb_pdu_decimal(struct soap*, const char*, int, const struct mb_pdu_decimal *, const char*);
SOAP_FMAC3 struct mb_pdu_decimal * SOAP_FMAC4 soap_get_mb_pdu_decimal(struct soap*, struct mb_pdu_decimal *, const char*, const char*);
SOAP_FMAC3 struct mb_pdu_decimal * SOAP_FMAC4 soap_in_mb_pdu_decimal(struct soap*, const char*, struct mb_pdu_decimal *, const char*);

#ifndef SOAP_TYPE_ARREGLO_type
#define SOAP_TYPE_ARREGLO_type (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ARREGLO_type(struct soap*, struct ARREGLO_type *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ARREGLO_type(struct soap*, struct ARREGLO_type const*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ARREGLO_type(struct soap*, const struct ARREGLO_type *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ARREGLO_type(struct soap*, const char*, int, const struct ARREGLO_type *, const char*);
SOAP_FMAC3 struct ARREGLO_type * SOAP_FMAC4 soap_get_ARREGLO_type(struct soap*, struct ARREGLO_type *, const char*, const char*);
SOAP_FMAC3 struct ARREGLO_type * SOAP_FMAC4 soap_in_ARREGLO_type(struct soap*, const char*, struct ARREGLO_type *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTomb_master_config
#define SOAP_TYPE_PointerTomb_master_config (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomb_master_config(struct soap*, struct mb_master_config *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomb_master_config(struct soap*, struct mb_master_config *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomb_master_config(struct soap*, const char *, int, struct mb_master_config *const*, const char *);
SOAP_FMAC3 struct mb_master_config ** SOAP_FMAC4 soap_get_PointerTomb_master_config(struct soap*, struct mb_master_config **, const char*, const char*);
SOAP_FMAC3 struct mb_master_config ** SOAP_FMAC4 soap_in_PointerTomb_master_config(struct soap*, const char*, struct mb_master_config **, const char*);

#ifndef SOAP_TYPE_PointerTomb_pdu_decimal
#define SOAP_TYPE_PointerTomb_pdu_decimal (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomb_pdu_decimal(struct soap*, struct mb_pdu_decimal *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomb_pdu_decimal(struct soap*, struct mb_pdu_decimal *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomb_pdu_decimal(struct soap*, const char *, int, struct mb_pdu_decimal *const*, const char *);
SOAP_FMAC3 struct mb_pdu_decimal ** SOAP_FMAC4 soap_get_PointerTomb_pdu_decimal(struct soap*, struct mb_pdu_decimal **, const char*, const char*);
SOAP_FMAC3 struct mb_pdu_decimal ** SOAP_FMAC4 soap_in_PointerTomb_pdu_decimal(struct soap*, const char*, struct mb_pdu_decimal **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
